
generate_knowledge_triples_hotpotqa_examplars = [
    # 1 - 5
    {
        "title": "Ellen Glasgow",
        "text": "Ellen Anderson Gholson Glasgow (April 22, 1873 \u2013 November 21, 1945) was an American novelist who portrayed the changing world of the contemporary South.",
        "triples": "<Ellen Glasgow; full name; Ellen Anderson Gholson Glasgow>\n<Ellen Glasgow; date of birth; April 22, 1873>\n<Ellen Glasgow; date of death; November 21, 1945>\n<Ellen Glasgow; nationality; American>\n<Ellen Glasgow; profession; novelist>\n<Ellen Glasgow; thematic focus; portrayed the changing world of the contemporary South>", 
    },
    {
        "title": "Morghem's .500 Nitro Express",
        "text": "Morghem's .500 Nitro Express known as Frank's Khing at owner/call name registered events, is a UKC registered male American Pit Bull Terrier. Who competes in dog sports and conformation shows earning titles in Dock Jump, Lure Course, Show Champion, Rally Obedience and Weight Pull. Khing has been awarded the AKC Canine Good Citizen and USTTA temperament tested certifications.",
        "triples": "<Morghem's .500 Nitro Express; also known as; Frank's Khing>\n<Morghem's .500 Nitro Express; registered with; UKC>\n<Morghem's .500 Nitro Express; breed; male American Pit Bull Terrier>\n<Morghem's .500 Nitro Express; competes in; dog sports, conformation shows>\n<Morghem's .500 Nitro Express; titles earned; Dock Jump, Lure Course, Show Champion, Rally Obedience, Weight Pull>\n<Morghem's .500 Nitro Express; awarded; AKC Canine Good Citizen, USTTA temperament tested certifications>", 
    },
    {
        "title": "1999 du Maurier Open \u2013 Men's Doubles",
        "text": "Martin Damm and Jim Grabb were the defending champions, but competed this year with different partners. Damm teamed up with Max Mirnyi and lost in second round to Ellis Ferreira and Rick Leach, while Grabb teamed up with Goran Ivani\u0161evi\u0107 and lost in quarterfinals also against Ferreira-Leach.",
        "triples": "<1999 du Maurier Open \u2013 Men's Doubles; defending champions; Martin Damm, Jim Grabb>\n<Martin Damm; teamed up with; Max Mirnyi>\n<Martin Damm and Max Mirnyi; lost to; Ellis Ferreira, Rick Leach in second round>\n<Jim Grabb; teamed up with; Goran Ivani\u0161evi\u0107>\n<Jim Grabb and Goran Ivani\u0161evi\u0107; lost to; Ellis Ferreira, Rick Leach in quarterfinals>"
    },
    {
        "title": "David Majzlin",
        "text": "David Majzlin is an Emmy\u00ae-nominated composer whose credits include numerous critically acclaimed films such as \"The Loving Story\", \"Youth Knows No Pain\", and \"Sins of My Father\" (\"Pecados De Mi Padre\") for HBO, \"Herb and Dorothy\", \"Stille\", (Winner - Best Score - Avignon Film Festival), \"Being Reel\", (Winner - Grand Prize - Project Greenlight Competition), and \"Shenandoah\" ( Louverture Films, Netflix), directed by Pulitzer Prize-winning photographer, David Turnley. He also wrote additional music for \"Diana Vreeland: The Eye Has To Travel\" (Samuel Goldwyn Films, Venice Film Festival, Toronto International Film Festival), \"Sunshine Cleaning\" (Nomination - Grand Jury Prize - Sundance Film Festival) - starring Amy Adams, Emily Blunt, and Alan Arkin, and source music for \"The Ghost Writer\" (dir., Roman Polanski, starring Ewan McGregor, Pierce Brosnan, Kim Catrall), \"All Good Things\" (dir., Andrew Jarecki, starring Ryan Gosling, Kirsten Dunst, Frank Langella), and \"The Joneses\" (starring Demi Moore, David Duchovny, and Lauren Hutton).",
        "triples": "<David Majzlin; profession; Emmy\u00ae-nominated composer>\n<David Majzlin; credits include; \"The Loving Story\", \"Youth Knows No Pain\", \"Sins of My Father\" (\"Pecados De Mi Padre\") for HBO>\n<David Majzlin; credits include; \"Herb and Dorothy\", \"Stille\", \"Being Reel\", \"Shenandoah\">\n<Stille; award; Winner - Best Score - Avignon Film Festival>\n<Being Reel; award; Winner - Grand Prize - Project Greenlight Competition>\n<Shenandoah; directed by; Pulitzer Prize-winning photographer, David Turnley>\n<David Majzlin; additional music credits; \"Diana Vreeland: The Eye Has To Travel\", \"Sunshine Cleaning\">\n<Diana Vreeland: The Eye Has To Travel; festivals; Samuel Goldwyn Films, Venice Film Festival, Toronto International Film Festival>\n<Sunshine Cleaning; recognition; Nomination - Grand Jury Prize - Sundance Film Festival>\n<Sunshine Cleaning; cast; Amy Adams, Emily Blunt, Alan Arkin>\n<David Majzlin; source music credits; \"The Ghost Writer\", \"All Good Things\", \"The Joneses\">\n<The Ghost Writer; director; Roman Polanski>\n<The Ghost Writer; cast; Ewan McGregor, Pierce Brosnan, Kim Catrall>\n<All Good Things; director; Andrew Jarecki>\n<All Good Things; cast; Ryan Gosling, Kirsten Dunst, Frank Langella>\n<The Joneses; cast; Demi Moore, David Duchovny, Lauren Hutton>", 
    },
    {
        "title": "Heinrich von B\u00fclow (Grotekop)",
        "text": "Heinrich von B\u00fclow also known as Big Top (Grotekop) was a knight born in the middle of the fourteenth century. He died either before 1395 or during 1415. He prospered as a warrior-supporter of Prince Albrecht of Mecklenburg (and of Sweden). Outside Mecklenberg, Heinrich Grotekop is still remembered in many quarters as an archetypal robber baron on account of his appetite for feuding.", 
        "triples": "<Heinrich von B\u00fclow (Grotekop); also known as; Big Top (Grotekop)>\n<Heinrich von B\u00fclow (Grotekop); was; a knight>\n<Heinrich von B\u00fclow (Grotekop); born; in the middle of the fourteenth century>\n<Heinrich von B\u00fclow (Grotekop); died; either before 1395 or during 1415>\n<Heinrich von B\u00fclow (Grotekop); prospered as a warrior-supporter of; Prince Albrecht of Mecklenburg (and of Sweden)>\n<Heinrich von B\u00fclow (Grotekop); is remembered as; an archetypal robber baron>\n<Heinrich von B\u00fclow (Grotekop); had; an appetite for feuding>\n<Heinrich von B\u00fclow (Grotekop); is remembered; outside Mecklenberg>",
    },
    # 6 - 10 
    {
        "title": "All the Way (Craig David song)",
        "text": "\"All the Way\" is the first single released by the British singer Craig David from his third album \"The Story Goes...\". It was the first single he released with new label Warner Bros. Records after Wildstar Records went bankrupt. After missing the top ten with previous singles \"World Filled with Love\" and \"You Don't Miss Your Water ('Til the Well Runs Dry)\", \"All The Way\" returned David to the top three. It was the highest-charting single from \"The Story Goes...\" but not the biggest-selling as \"Don't Love You No More (I'm Sorry)\" spent over double the amount of weeks inside the UK top 75. The music video became the sixth Craig David video directed by Max & Dania.",
        "triples": "<All the Way; first single by; British singer Craig David>\n<All the Way; from album; Craig David's third album \"The Story Goes...\">\n<Craig David; released with; Warner Bros. Records>\n<Craig David; previously released with; Wildstar Records>\n<Wildstar Records; status; went bankrupt>\n<Craig David; previous singles; \"World Filled with Love\" and \"You Don't Miss Your Water ('Til the Well Runs Dry)\">\n<All the Way; chart performance; returned Craig David to the top three>\n<All the Way; highest-charting single from; The Story Goes...>\n<Don't Love You No More (I'm Sorry); comparison; spent over double the amount of weeks inside the UK top 75 than All the Way>\n<All the Way; music video director; Max & Dania>\n<All the Way; music video number; sixth Craig David video directed by Max & Dania>"
    },
    {
        "title": "Chuck Essegian",
        "text": "Charles Abraham \"Chuck\" Essegian (born August 9, 1931) is an American former professional baseball left fielder. He played in Major League Baseball (MLB) the Philadelphia Phillies, St. Louis Cardinals, Los Angeles Dodgers, Baltimore Orioles, Kansas City Athletics, and Cleveland Indians. He also played one season in Nippon Professional Baseball (NPB) for the Kintetsu Buffaloes.",
        "triples": "<Chuck Essegian; full name; Charles Abraham \"Chuck\" Essegian>\n<Chuck Essegian; date of birth; August 9, 1931>\n<Chuck Essegian; nationality; American>\n<Chuck Essegian; profession; former professional baseball left fielder>\n<Chuck Essegian; played in; Major League Baseball (MLB)>\n<Chuck Essegian; MLB teams; Philadelphia Phillies, St. Louis Cardinals, Los Angeles Dodgers, Baltimore Orioles, Kansas City Athletics, Cleveland Indians>\n<Chuck Essegian; also played in; Nippon Professional Baseball (NPB)>\n<Chuck Essegian; NPB team; Kintetsu Buffaloes>\n<Chuck Essegian; seasons in NPB; one>",
    },
    {
        "title": "Pacific International Enterprises",
        "text": "Pacific International Enterprises (PIE) is an American film production company and film distributor, founded by Arthur R. Dubs as a producer of family films. PIE is a privately held company that has been in business for over thirty years as \"\"A Universal Force in Family Film Entertainment\"\". Their films have been continually licensed and re-licensed for television by various channels such as HBO, Disney, TNT, CBS and in over 100 countries worldwide. Many of PIE's movies are filmed on location with outdoor scenery shots such as the state of Oregon in \"Sacred Ground\", the state of Utah in \"Windwalker\" and the state of Colorado for the three films of the \"Wilderness Family\" for example.",
        "triples": "<Pacific International Enterprises; abbreviation; PIE>\n<Pacific International Enterprises; country where the company is based; American>\n<Pacific International Enterprises; type; film production company and film distributor>\n<Pacific International Enterprises; founder; Arthur R. Dubs>\n<Pacific International Enterprises; focus; producer of family films>\n<Pacific International Enterprises; business status; privately held company>\n<Pacific International Enterprises; business duration; over thirty years>\n<Pacific International Enterprises; slogan; A Universal Force in Family Film Entertainment>\n<Pacific International Enterprises; licensing activity; films licensed and re-licensed for television>\n<Pacific International Enterprises; licensing channels; HBO, Disney, TNT, CBS>\n<Pacific International Enterprises; global reach; licensed in over 100 countries worldwide>\n<Sacred Ground; filming location; Oregon>\n<Windwalker; filming location; Utah>\n<Wilderness Family series; filming location; Colorado>", 
    },
    {
        "title": "Farley, New South Wales",
        "text": "Farley is a rural village in the City of Maitland in the Hunter Region of New South Wales, Australia. Early settler Captain Emanuel Hungerford arrived in New South Wales in 1828 before purchasing an established 2000 acre property named Lochdon. Here he built a homestead he called Farley House, from which Farley takes its name, after his ancestral home of Farleigh Hungerford, Somerset. The village is bordered to the north by the Main North railway line, and a station served the surrounding area from 1860 until 1975. The Farley Wastewater Treatment Works is located in a rural area south of the village.",
        "triples": "<Farley; type; rural village>\n<Farley; location; in the City of Maitland in the Hunter Region of New South Wales, Australia>\n<Captain Emanuel Hungerford; arrived in; New South Wales in 1828>\n<Captain Emanuel Hungerford; purchased; Lochdon>\n<Lochdon; size; 2000 acres>\n<Farley House; built by; Captain Emanuel Hungerford>\n<Farley; named after; Farley House>\n<Farley House; named after; Farleigh Hungerford, Somerset>\n<Farley; bordered to the north by; Main North railway line>\n<Main North railway line; had a station serving; Farley from 1860 until 1975>\n<Farley Wastewater Treatment Works; location; in a rural area south of the village>", 
    },
    {
        "title": "Nick Perry (writer)",
        "text": "Nick Perry is a British playwright and screenwriter. He is a graduate of the National Film and Television School. His first play Arrivederci Millwall was produced by The Combination at The Albany Empire, Deptford in 1985 and jointly won the Samuel Beckett Award. \"Smallholdings\" was first performed at the Kings Head Theatre in 1986, and \"The Vinegar Fly\" at the Soho Poly in 1988. \"Near Cricket St Thomas, 1919\" was directed by Alan Ayckbourn at the McCarthy Theatre, Scarborough in 1997. \"An Illustrated Talk\" was performed at the Newtown Theatre, Sydney, as part of the 2008 Short and Sweet festival. His radio play \"The Loop\" was broadcast on BBC Radio 4 in November 2009 and won a Sony Radio Academy bronze award. Andrew Scott was named Best Supporting Actor at the inaugural BBC Audio Drama awards in 2012 for his performance in Perry's radio play, \"Referee\".",
        "triples": "<Nick Perry; nationality; British>\n<Nick Perry; professions; playwright, screenwriter>\n<Nick Perry; graduate of; National Film and Television School>\n<Nick Perry; first play; Arrivederci Millwall>\n<Arrivederci Millwall; produced by; The Combination at The Albany Empire, Deptford>\n<Arrivederci Millwall; production year; 1985>\n<Arrivederci Millwall; award; jointly won the Samuel Beckett Award>\n<Smallholdings; first performed at; Kings Head Theatre in 1986>\n<The Vinegar Fly; first performed at; Soho Poly in 1988>\n<Near Cricket St Thomas, 1919; directed by; Alan Ayckbourn>\n<Near Cricket St Thomas, 1919; venue; McCarthy Theatre, Scarborough>\n<Near Cricket St Thomas, 1919; production year; 1997>\n<An Illustrated Talk; performed at; Newtown Theatre, Sydney>\n<An Illustrated Talk; part of; 2008 Short and Sweet festival>\n<The Loop; medium; radio play>\n<The Loop; broadcast on; BBC Radio 4>\n<The Loop; broadcast date; November 2009>\n<The Loop; award; won a Sony Radio Academy bronze award>\n<Referee; radio play by; Nick Perry>\n<Referee; actor award; Andrew Scott named Best Supporting Actor>\n<Referee; award event; inaugural BBC Audio Drama awards in 2012>",
    },
    # 11 - 15 
    {
        "title": "Todd David Lawhorne",
        "text": "Todd David Lawhorne is an American theatre and film actor. Member of AFTRA and AEA. Best known for his starring role as Dalton Monroe in \"In Plain Sight\" and his supporting role as Phil the skinhead in \"The Bros,\" starring Shaquille O'Neal and Joey Fatone. In New York City, he starred in numerous plays off and off-off Broadway, including \"Twelfth Night\" at Lincoln Center and Laertes in Pineapple Project's production of \"Hamlet.\" Resident actor of the Children's Theatre at the New York Hall of Science.",
        "triples": "<Todd David Lawhorne; nationality; American>\n<Todd David Lawhorne; occupation; theatre and film actor>\n<Todd David Lawhorne; memberships; AFTRA and AEA>\nTodd David Lawhorne; best known for; starring role as Dalton Monroe in \"In Plain Sight\", supporting role as Phil the skinhead in \"The Bros\">\n<The Bros; starring; Shaquille O'Neal, Joey Fatone>\n<Todd David Lawhorne; starred in; numerous plays off and off-off Broadway in New York City>\n<Todd David Lawhorne; roles in plays; Twelfth Night at Lincoln Center, Laertes in Pineapple Project's production of \"Hamlet\">\n<Todd David Lawhorne; resident actor of; Children's Theatre at the New York Hall of Science>", 
    },
    {
        "title": "Kelie McIver",
        "text": "Kelie McIver is a Kansas-born actress and singer who has played classical stage roles such as Lady Macbeth and Nurse in \"Romeo & Juliet\" for Kingsmen Shakespeare Festival, Viola in \"Twelfth Night\" for both Nevada Shakespeare in the Park and Shakespeare at Play, Hecuba in \"The Trojan Women\", Kate in \"Taming of the Shrew\", Rosalind in \"As You Like It\", Doll Common in Mark Ringer's production of \"The Alchemist\" and as both Puck and Titania in separate productions of \"A Midsummer Night's Dream\". She has also appeared in roles in non-classical plays such as \"Ravenscroft\", \"Train of Thought\", \"The Matchmaker\", \"Madwoman of Chaillot\", and Jon Mullich's adaptation of \"A Servant of Two Masters\". McIver is a frequent performer at the \"Golden Raspberry Awards\" (RAZZIES) ceremony and has toured with the country music trio Mama Says! with Janet Fisher and Patti Shannon. She is a former president and long standing board member of the Midwest Entertainment Connection (MECONN), a nonprofit organization that connects the entertainment industries of Los Angeles and the Midwest. Her film appearances include the award-winning short film \"Trail End\" opposite Barry Corbin and the 2009 feature film \"Table for Three.\"",
        "triples": "<Kelie McIver; birthplace; Kansas>\n<Kelie McIver; profession; actress and singer>\n<Kelie McIver; classical stage roles; Lady Macbeth and Nurse in \"Romeo & Juliet\", Viola in \"Twelfth Night\", Hecuba in \"The Trojan Women\", Kate in \"Taming of the Shrew\", Rosalind in \"As You Like It\", Doll Common in \"The Alchemist\", Puck and Titania in \"A Midsummer Night's Dream\">\n<Romeo & Juliet; festival; Kingsmen Shakespeare Festival>\n<Twelfth Night; performed at; Nevada Shakespeare in the Park, Shakespeare at Play>\n<The Alchemist; production by; Mark Ringer>\n<Kelie McIver; non-classical stage roles; \"Ravenscroft\", \"Train of Thought\", \"The Matchmaker\", \"Madwoman of Chaillot\", \"A Servant of Two Masters\" (Jon Mullich's adaptation)>\n<Kelie McIver; frequent performer at; Golden Raspberry Awards (RAZZIES) ceremony>\n<Kelie McIver; toured with; country music trio Mama Says!>\n<Mama Says!; members; Janet Fisher, Patti Shannon>\n<Kelie McIver; roles in former organization; president, board member of Midwest Entertainment Connection (MECONN)>\n<MECONN; description; nonprofit organization connecting entertainment industries of Los Angeles and the Midwest>\n<Kelie McIver; film appearances; award-winning short film \"Trail End\", 2009 feature film \"Table for Three\">\n<Trail End; film appearance; Kelie McIver opposite Barry Corbin>\n<Table for Three; film appearance; Kelie McIver>", 
    },
    {
        "title": "Gabriel (New-Gen)",
        "text": "John Gabriel is a fictional character, a superhero appearing in American comic books published by Marvel Comics. The character appears in the NEW-GEN comic books. Created by Chris Matonti, J.D. Matonti, and Julia Coppola, he first appeared in NEW-GEN #1 (2010). He is the founder and leader of the A.P.N.G., and the leading scientific mind in the field of nanotechnology on the world of New-Gen.",
        "triples": "<John Gabriel; is; a fictional character>\n<John Gabriel; role; superhero>\n<John Gabriel; appears in; American comic books published by Marvel Comics>\n<John Gabriel; comic series; NEW-GEN>\n<John Gabriel; creators; Chris Matonti, J.D. Matonti, Julia Coppola>\n<John Gabriel; first appeared in; NEW-GEN #1 (2010)>\n<John Gabriel; position; founder and leader of the A.P.N.G.>\n<John Gabriel; expertise; leading scientific mind in the field of nanotechnology>\n<John Gabriel; location; world of New-Gen>", 
    },
    {
        "title": "Independent Hill, Virginia",
        "text": "Independent Hill is an unincorporated town in Prince William County, Virginia. It is located along State Route 234 at the intersection with Joplin Road. The only visible remaining businesses seem to be Samsky's Market (also a Citgo gas station) and Crosby's Crab Company. In early 2006, a realignment of 234 bypassed the town, leaving it on a side road. The greater Independent Hill area is defined by the Census Bureau as a census-designated place (CDP), with a population of 7,419 as of 2010.",
        "triples": "<Independent Hill; type; unincorporated town>\n<Independent Hill; location; in Prince William County, Virginia>\n<Independent Hill; located along; State Route 234 at the intersection with Joplin Road>\n<Independent Hill; remaining businesses; Samsky's Market (also a Citgo gas station), Crosby's Crab Company>\n<State Route 234; realignment; bypassed Independent Hill in early 2006>\n<Independent Hill; result of bypass of Route 243; left on a side road>\n<Independent Hill area; classification; census-designated place (CDP)>\n<Independent Hill; population; 7,419 as of 2010>", 
    },
    {
        "title": "2000 Sports Racing World Cup",
        "text": "The 2000 Sports Racing World Cup was the fourth season of Sports Racing World Cup (later known as the FIA Sportscar Championship). It was a series for sportscar style prototypes broken into two classes based on power and weight, called SR and SRL (or SR2). It began on March 26, 2000 and ended November 26, 2000 after 10 races. The two American rounds were run in conjunction with Grand American Road Racing Championship, using similar SR rules.",
        "triples": "<2000 Sports Racing World Cup; season number; fourth season of Sports Racing World Cup>\n<2000 Sports Racing World Cup; later known as; FIA Sportscar Championship>\n<2000 Sports Racing World Cup; series type; sportscar style prototypes>\n<2000 Sports Racing World Cup; classes based on power and weight; SR, SRL (or SR2)>\n<2000 Sports Racing World Cup; start date; March 26, 2000>\n<2000 Sports Racing World Cup; end date; November 26, 2000>\n<2000 Sports Racing World Cup; number of races; 10>\n<2000 Sports Racing World Cup; American rounds ran with; Grand American Road Racing Championship>\n<2000 Sports Racing World Cup; rules; similar SR rules>",
    },
    # 16 - 20 
    {
        "title": "Game Dev Story",
        "text": "Game Dev Story is a simulation video game developed and published by Kairosoft for Microsoft Windows, iOS, and Android. It was released for Windows in April of 1997 , for iOS and Android on October 9, 2010, and for Windows Phone on July 6, 2015. The game follows a player-controlled video game company and its attempts to expand into a sales powerhouse over time. As a simulation, the game and the direction of the company is controlled by the player, following a parallel timeline of the video game industry and its history. The game was released to positive reviews, with many reviewers focusing on \"Game Dev Story\"' s addictive aspects and its witty references to video game pop culture.",
        "triples": "<Game Dev Story; type; simulation video game>\n<Game Dev Story; developed and published by; Kairosoft>\n<Game Dev Story; platforms; Microsoft Windows, iOS, Android>\n<Game Dev Story; Windows release date; April 1997>\n<Game Dev Story; iOS and Android release date; October 9, 2010>\n<Game Dev Story; Windows Phone release date; July 6, 2015>\n<Game Dev Story; gameplay; follows a player-controlled video game company>\n<Game Dev Story; goal; expand into a sales powerhouse>\n<Game Dev Story; game control; controlled by the player>\n<Game Dev Story; thematic elements; follows a parallel timeline of the video game industry and its history>\n<Game Dev Story; received; positive reviews>\n<Game Dev Story; reviewers focused on; addictive aspects, witty references to video game pop culture>", 
    },
    {
        "title": "Andrew Szanton",
        "text": "Andrew Szanton (born in Washington, D.C. in 1963) is an American collaborative memoirist. During his career he has worked with a wide range of subjects including civil rights pioneer Charles Evers, Nobel Prize winning physicist Eugene Wigner, former co-chairman of Goldman Sachs John Whitehead, former United States Senator Edward Brooke, founding director of Xerox PARC George Pake, eminent surgeon Dr. Charles Epps, head of the Missouri Botanical Garden Peter Raven, and former Boston mayor Raymond Flynn.",
        "triples": "<Andrew Szanton; birth year; 1963>\n<Andrew Szanton; place of birth; Washington, D.C.>\n<Andrew Szanton; nationality; American>\n<Andrew Szanton; profession; collaborative memoirist>\n<Andrew Szanton; worked with; Charles Evers, Eugene Wigner, John Whitehead, Edward Brooke, George Pake, Charles Epps, Peter Raven, Raymond Flynn>\n<Charles Evers; description; civil rights pioneer>\n<Eugene Wigner; description; Nobel Prize winning physicist>\n<John Whitehead; previous role; co-chairman of Goldman Sachs>\n<Edward Brooke; previous role; United States Senator>\n<George Pake; previous role; founding director of Xerox PARC>\n<Charles Epps; description; eminent surgeon>\n<Peter Raven; role; head of Missouri Botanical Garden>\n<Raymond Flynn; previous role; Boston mayor>", 
    },
    {
        "title": "Inaindha Kaigal",
        "text": "Inaindha Kaigal (English: Conjoined Hands ) is a 1990 Indian Tamil film, directed by N. K. Vishwanathan. The film features C. Arunpandian, Ramki, Nirosha and Sindhu in lead roles, with Nassar, Senthil, Srividya, Murali Kumar and Prabhakaran playing supporting roles. The film, produced by Aabavanan who also wrote the script and lyrics, had musical score by Gyan Varma and was released on 2 August 1990. The film is a blockbuster in the year 1990 and became a successful venture. The film has been dubbed in Hindi as \"Aakhri Sangam\" and in Telugu as Sahasa Ghattam.", 
        "triples": "<Inaindha Kaigal; English title; Conjoined Hands>\n<Inaindha Kaigal; type; Indian Tamil film>\n<Inaindha Kaigal; release year; 1990>\n<Inaindha Kaigal; director; N. K. Vishwanathan>\n<Inaindha Kaigal; lead actors; C. Arunpandian, Ramki, Nirosha, Sindhu>\n<Inaindha Kaigal; supporting actors; Nassar, Senthil, Srividya, Murali Kumar, Prabhakaran>\n<Inaindha Kaigal; producer; Aabavanan>\n<Aabavanan; roles in Inaindha Kaigal; scriptwriter, lyricist>\n<Inaindha Kaigal; music composer; Gyan Varma>\n<Inaindha Kaigal; release date; 2 August 1990>\n<Inaindha Kaigal; status; blockbuster in 1990>\n<Inaindha Kaigal; dubbed in; Hindi as \"Aakhri Sangam\", Telugu as \"Sahasa Ghattam\">", 
    },
    {
        "title": "Wonky (album)",
        "text": "Wonky is the eight studio album by Orbital, released on their own ACP label (via Warner Music Group/Alternative Distribution Alliance) in the UK on 2 April 2012, and exclusively through iTunes in the USA and Canada on 17 April 2012. The album is their first since the \"Blue Album\" in 2004 and the first since they reformed in 2008. It features vocals from Zola Jesus and Lady Leshurr. The album was taken off of Spotify and iTunes in the United States for unknown reasons. There are some songs you cannot find at all in their original versions, like Beelzedub or Distractions.",
        "triples": "<Wonky; type; album>\n<Wonky; artist; Orbital>\n<Wonky; album number; eighth studio album>\n<Wonky; record label; ACP label>\n<Wonky; distribution; Warner Music Group/Alternative Distribution Alliance in the UK, iTunes in the USA and Canada>\n<Wonky; UK release date; 2 April 2012>\n<Wonky; USA and Canada release date; 17 April 2012>\n<Wonky; status; first album since the \"Blue Album\" in 2004>\n<Wonky; status; first album since reforming in 2008>\n<Wonky; features vocals from; Zola Jesus, Lady Leshurr>\n<Wonky; availability; taken off Spotify and iTunes in the USA>\n<Wonky; songs unavailable in original versions; Beelzedub, Distractions>", 
    },
    {
        "title": "United States v. Silk",
        "text": "United States v. Silk, 331 U.S. 704 (1947) , was a United States Supreme Court case regarding US labor law. The case concerned the scope of protection for employees under the Social Security Act 1935.",
        "triples": "<United States v. Silk; case number; 331 U.S. 704 (1947)>\n<United States v. Silk; type; United States Supreme Court case>\n<United States v. Silk; concerned; US labor law>\n<United States v. Silk; scope; protection for employees>\n<United States v. Silk; under; Social Security Act 1935>", 
    },
]
