
generate_knowledge_triples_wikipedia_examplars = [
    # 1 - 5 
    {
        "title": "Mephisto (tank)", 
        "text": "of Australia reviewed it favourably in 2014. The work contains a small number of historical and technical errors. Mephisto appears as a visual overhaul (skin) in the 2016 first-person shooter \"Battlefield 1\". Mephisto (tank) Mephisto is a World War I German tank, the only surviving example of an A7V. In April 1918, during a German attack at Villers-Bretonneux on the Western Front, it became stuck in a shell-hole and was abandoned by its crew. It was later recovered by Allied troops and, after the war, taken to Australia as a trophy. Mephisto is housed at the Queensland Museum, in Brisbane,", 
        "triples": "<Mephisto (tank); review; favourably in 2014>\n<Mephisto (tank); contains; a small number of historical and technical errors>\n<Mephisto (tank); appears as; a visual overhaul (skin) in the 2016 first-person shooter \"Battlefield 1\">\n<Mephisto (tank); type; World War I German tank>\n<Mephisto (tank); status; only surviving example of an A7V>\n<Mephisto (tank); became stuck in; a shell-hole during a German attack at Villers-Bretonneux on the Western Front, abandoned by its crew in April 1918>\n<Mephisto (tank); recovered by; Allied troops>\n<Mephisto (tank); taken to; Australia as a trophy>\n<Mephisto (tank); is housed at; Queensland Museum, Brisbane>", 
    },
    {
        "title": "Santa Catalina Island (California)", 
        "text": "adjacent to the Sheriff's office. The USC Wrigley Marine Science Center houses research and teaching facilities at Big Fisherman's Cove, near Two Harbors, for the USC Wrigley Institute for Environmental Studies. Maintained by the University of Southern California and named for Philip K. Wrigley, it consists of a laboratory building, dormitory housing, cafeteria, a hyperbaric chamber, and a large waterfront staging area complete with dock, pier, helipad, and diving lockers. The facility was made possible by a donation from the Wrigley family in 1995. The institute welcomes the public to visit as part of it's Saturdays at the Lab program.", 
        "triples": "<USC Wrigley Marine Science Center; houses; research and teaching facilities at Big Fisherman's Cove, near Two Harbors, for the USC Wrigley Institute for Environmental Studies>\n<USC Wrigley Marine Science Center; is maintained by; the University of Southern California>\n<USC Wrigley Marine Science Center; is named for; Philip K. Wrigley>\n<USC Wrigley Marine Science Center; consists of; a laboratory building, dormitory housing, cafeteria, a hyperbaric chamber, and a large waterfront staging area complete with dock, pier, helipad, and diving lockers>\n<USC Wrigley Marine Science Center; was made possible by; a donation from the Wrigley family in 1995>\n<USC Wrigley Marine Science Center; welcomes; the public to visit as part of its Saturdays at the Lab program>", 
    },
    {
        "title": "Virgil Goode 2012 presidential campaign", 
        "text": "had \"expressed a strong interest\" in the nomination. Thereafter, Goode told \"The Roanoke Times\" that he would \"consider it as the year progresses\". Clymer informed the publication that \"There's nothing that I can see now that would prevent him from getting the nomination were he to say he indeed wants it.\" In reaction to the possibility, Goode's 2008 congressional campaign manager Tucker Watkins said Goode would be an upgrade from the Constitution Party's 2008 nominee Chuck Baldwin, who appeared on 37 state ballots and won 0.15 percent of the popular vote. However, Watkins admitted that he \"can't imagine [Goode] flying", 
        "triples": "<Virgil Goode; told; \"The Roanoke Times\" that he would \"consider it as the year progresses\">\n<Clymer; informed; the publication that \"There's nothing that I can see now that would prevent him from getting the nomination were he to say he indeed wants it\">\n<Virgil Goode 2012 presidential campaign; manager; Tucker Watkins>\n<Tucker Watkins; said; Goode would be an upgrade from the Constitution Party's 2008 nominee Chuck Baldwin>\n<Chuck Baldwin; appeared on; 37 state ballots>\n<Chuck Baldwin; won; 0.15 percent of the popular vote>\n<Tucker Watkins; admitted; that he \"can't imagine [Goode] flying\">",
    },
    {
        "title": "Ian Bradley (naval officer)", 
        "text": "His command of Waikato included the dramatic rescue of an ill Russian Seaman from a Soviet trawler south of Stewart Island (the helicopter crew were awarded bravery medals). A long deployment to Canada and the US West Coast followed; during that time Waikato was integrated into a US Navy Destroyer Squadron \u2013 a unique step for the two navies. While on one major exercise a US Navy helicopter reported an inflight emergency and needed to land. Although the exercise commander ordered another frigate (without a flight deck) to rescue the air crew (implicitly accepting the loss of the helicopter) Ian", 
        "triples": "<Ian Bradley (naval officer); commanded; Waikato>\n<Waikato; included the dramatic rescue of; an ill Russian Seaman from a Soviet trawler south of Stewart Island>\n<the helicopter crew; were awarded; bravery medals>\n<Waikato; had; a long deployment to Canada and the US West Coast>\n<Waikato; was integrated into; a US Navy Destroyer Squadron>\n<Waikato's integration into a US Navy Destroyer Squadron; was; a unique step for the two navies>\n<US Navy helicopter; reported; an inflight emergency>\n<US Navy helicopter; needed; to land>\n<the exercise commander; ordered; another frigate (without a flight deck) to rescue the air crew>\n<the exercise commander; implicitly accepted; the loss of the helicopter>", 
    },
    {
        "title": "Beverley Shenstone", 
        "text": "Mitchell with additional input from Ernest Mansbridge, Joe Smith and Alfred Faddy began to investigate using an elliptical wing. Both Mitchell and Stenstone were aware of the potential of an elliptical wing as Mitchell had proposed it for his Type 179 flying boat, while the Short Crusader seaplane which had been an entry for the 1927 Schneider Trophy had one. Meanwhile Shenstone was aware that Frederick Lanchester had suggested in 1907 that it was better to spread the vortex flow along the wing instead of concentrating it at the tip. while Max Munk had also identified that when a wing", 
        "triples": "<Mitchell; began to investigate; using an elliptical wing>\n<Mitchell; had additional input from; Ernest Mansbridge, Joe Smith, Alfred Faddy>\n<Mitchell and Shenstone; were aware of; the potential of an elliptical wing>\n<Mitchell; had proposed; an elliptical wing for his Type 179 flying boat>\n<Short Crusader seaplane; had; an elliptical wing>\n<Short Crusader seaplane; was; an entry for the 1927 Schneider Trophy>\n<Shenstone; was aware that; Frederick Lanchester had suggested in 1907 that it was better to spread the vortex flow along the wing instead of concentrating it at the tip>",
    },
    # 6 - 10 
    {
        "title": "Geographical distribution of Russian speakers", 
        "text": "facto\" Russification. The Soviet system heavily promoted the Russian language as the \"language of inter-ethnic communication\". Eventually, in 1990, Russian became legally the official all-Union language of the Soviet Union, with constituent republics having rights to declare their own official languages. After the dissolution of the Soviet Union in 1991, about 25 million Russians (about 1/6 of former Soviet Russians) found themselves outside Russia, which constitutes about 10% of the population of the post-Soviet states other than Russia. Many millions of them subsequently became refugees due to various inter-ethnic conflicts. In Armenia Russian has no official status, but it's recognized", 
        "triples": "<Russian language; promoted by; the Soviet system as the \"language of inter-ethnic communication\">\n<Russian; became; the official all-Union language of the Soviet Union in 1990>\n<constituent republics; having rights to declare; their own official languages>\n<Soviet Union; dissolution year; 1991>\n<dissolution of the Soviet Union; resulted in; about 25 million Russians (about 1/6 of former Soviet Russians) found themselves outside Russia>\n<Russians outside Russia; constitute; about 10% of the population of post-Soviet states other than Russia>\n<Many millions of Russians; became; refugees due to various inter-ethnic conflicts>\n<Russian in Armenia; has; no official status, but it's recognized>",
    },
    {
        "title": "Shane Balkowitsch", 
        "text": "found raped, mutilated, and burned by the roadside in the Zekeriyak\u00f6y up-market on August 12, 2016. It is part of the global outcry and protests against the hate, mistreatment, and irrational fear of transgender people. \"The Mask Series\" was started by Shane Balkowitsch in 2012 after taking a very simple collodion image of a vintage Czech M10 gas mask and a wilting flower. He called the plate \'The Last Flower\'. The goal for this series is to raise awareness of the historic wet plate technique as an art form. This will allow artists that normally do not have a chance", 
        "triples": "<victim; was found; raped, mutilated, and burned by the roadside in the Zekeriyak\u00f6y up-market on August 12, 2016>\n<incident; is part of; the global outcry and protests against the hate, mistreatment, and irrational fear of transgender people>\n<Shane Balkowitsch; started; \"The Mask Series\" in 2012>\n<Shane Balkowitsch; started \"The Mask Series\" after taking; a very simple collodion image of a vintage Czech M10 gas mask and a wilting flower>\n<Shane Balkowitsch; called the plate; 'The Last Flower'>\n<The Mask Series; goal; to raise awareness of the historic wet plate technique as an art form>\n",
    },
    {
        "title": "Myriopteris maxoniana", 
        "text": "folded edge of a segment lobe. The edges of the leaf are not noticeably differentiated from the bulk of the leaf tissue where they fold over the sporangia. The spores in the sporangia are dark brown in color. \"Myriopteris maxoniana\" closely resembles \"Myriopteris longipila\". However, that species tends to be narrowly triangular (widest at the base) to broadly oblong (widest near the tip), and has denser and shorter hairs covering the blade. William Ralph Maxon originally suggested that the type specimen might be a distinct species. However, his suggestion was not taken up until 2004, when John Mickel first described", 
        "triples": "<edges of the leaf; are not noticeably differentiated from; the bulk of the leaf tissue where they fold over the sporangia>\n<spores in the sporangia; are; dark brown in color>\n<Myriopteris maxoniana; closely resembles; Myriopteris longipila>\n<Myriopteris longipila; tends to be; narrowly triangular (widest at the base) to broadly oblong (widest near the tip)>\n<Myriopteris longipila; has; denser and shorter hairs covering the blade>\n<William Ralph Maxon; originally suggested; that the type specimen might be a distinct species>\n<Maxon's suggestion; was not taken up until; 2004>\n<John Mickel; first described; Myriopteris maxoniana as a distinct species in 2004>",
    },
    {
        "title": "Charles R. Weatherhogg", 
        "text": "about 1893-1897. They had a branch office in Muncie and designed a number of large homes in that city. Their most important project together was the Jasper County Courthouse, 1897, also in Rensselaer. Grindle first received the commission for the Jasper County Courthouse, then brought in Weatherhogg. Grindle left the project entirely to Weatherhogg, who then completed most of the design work. The courthouse is an imposing three story limestone building with tower executed in the Chateauesque/Tudor Revival style. Weatherhogg went on to design a number of buildings in Fort Wayne, including several schools, the Masonic Temple, Blackstone Building, Fairfield", 
        "triples": "<Charles R. Weatherhogg; worked with Grindle; about 1893-1897>\n<Charles R. Weatherhogg and Grindle; had a branch office in; Muncie>\n<Charles R. Weatherhogg and Grindle; designed; a number of large homes in Muncie>\n<Charles R. Weatherhogg and Grindle; the most important project together; the Jasper County Courthouse, 1897, in Rensselaer>\n<Grindle; first received; the commission for the Jasper County Courthouse>\n<Grindle; brought in; Weatherhogg to the Jasper County Courthouse>\n<Grindle; left; the project entirely to Weatherhogg>\n<Weatherhogg; completed; most of the design work for the Jasper County Courthouse>\n<Jasper County Courthouse; is; an imposing three story limestone building with tower executed in the Chateauesque/Tudor Revival style>\n<Weatherhogg; went on to design; a number of buildings in Fort Wayne>\n<Weatherhogg's designs in Fort Wayne; included; several schools, the Masonic Temple, Blackstone Building, Fairfield>",
    },
    {
        "title": "Macquarie Field House", 
        "text": "sought the help of convict clearing gangs and between June 1822 and June 1823 were cleared. Meehan used Macquariefield primarily for stock and only secondarily for cropping. The first house built on this site, 'Meehan's Castle', built but possibly not completed until 1818, was a two-storey structure of even greater prominence on the then bare hill than the later (and remaining) house which was built in the 1840s. Meehan chose its site because it was the only strategic outcrop in the region, effectively being a naturally fortified rampart with panoramic views. This was important for both security and observation, in", 
        "triples": "<Meehan; used; Macquariefield primarily for stock and only secondarily for cropping>\n<first house on this site; was; Meehan's Castle>\n<Meehan's Castle; was built; but possibly not completed until 1818>\n<Meehan's Castle; was; a two-storey structure of even greater prominence on the then bare hill than the later house built in the 1840s>\n<Meehan; chose its site because; it was the only strategic outcrop in the region, effectively being a naturally fortified rampart with panoramic views>\n",
    },
    # 11 - 15 
    {
        "title": "Palmerton Area School District", 
        "text": "years, which the union rejected. State law gives the Pennsylvania Department of Education the power to order the teachers to return so that students will complete 180 days of instruction, by June 15. The teacher's union ended the strike effective January 23, 2017. Pennsylvania is one of 13 states in which teacher strikes are legal. Pennsylvania has the highest rate of teacher strikes in the United States. In 2016, there were many teacher union strikes including in: Line Mountain School District, Warren County School District, Shamokin Area School District, Highlands School District, Montrose Area School District, Ambridge Area School District,", 
        "triples": "<State law; gives; the Pennsylvania Department of Education the power to order the teachers to return for 180 days of instruction by June 15>\n<teacher's union; ended; the strike effective January 23, 2017>\n<Pennsylvania; is one of; 13 states in which teacher strikes are legal>\n<Pennsylvania; has; the highest rate of teacher strikes in the United States>\n<teacher union strikes in 2016; occurred in; Line Mountain School District, Warren County School District, Shamokin Area School District, Highlands School District, Montrose Area School District, Ambridge Area School District>",
    },
    {
        "title": "Schei\u00dfe (song)", 
        "text": "at number 90, after Gaga had included parts of it in her performance at the \"Germany's Next Topmodel\" TV show. Following the release of \"Born This Way,\" \"Schei\u00dfe\" peaked at number 13 on the International Digital Download chart in South Korea, jumping 21 positions from the previous week. It also peaked at number 136 on the UK Singles Chart, for one week. In the United States, the song reached number 11 on the Bubbling Under Hot 100 Singles chart of \"Billboard\". It also charted at number six on the Dance/Electronic Digital Songs, as well as at number 72 on the", 
        "triples": "<Schei\u00dfe; chart at; number 90 after Gaga included parts of it in her performance at the \"Germany's Next Topmodel\" TV show>\n<Schei\u00dfe; peaked at; number 13 on the International Digital Download chart in South Korea>\n<Schei\u00dfe; jumped; 21 positions from the previous week in South Korea>\n<Schei\u00dfe; peaked at; number 136 on the UK Singles Chart for one week>\n<Schei\u00dfe; reached; number 11 on the Bubbling Under Hot 100 Singles chart of \"Billboard\" in the United States>\n<Schei\u00dfe; chart at; number six on the Dance/Electronic Digital Songs chart in the United States>\n<Schei\u00dfe; charted at; number 72 on the>",
    },
    {
        "title": "Tongan Guanzhi", 
        "text": "Daopi. In fact, it states Daopi has no students at all. The \"Transmission of the Lamp\" instead claims that Tongan Guanzhi is the disciple of Tongan Wei, in turn a student of Jufeng Puman, with Jufeng being an apparently obscure student of the famous Dongshan Liangjie. Both Tongan Wei and Jufeng Puman are listed for the first time in the \"Transmission of the Lamp\", and neither with much information. However, Dayang Jingxuan, who in Huihong's version of the lineage is a descendant of Tonagan Daopi, is recorded in the \"Transmission of the Lamp\" as being descended through Jufeng Puman and", 
        "triples": "<Transmission of the Lamp; claims; Tongan Guanzhi is the disciple of Tongan Wei>\n<Tongan Wei; is a student of; Jufeng Puman>\n<Jufeng Puman; is a student of; Dongshan Liangjie>\n<Tongan Wei, Jufeng Puman; are listed for the first time in; Transmission of the Lamp>\n<Transmission of the Lamp; lists; little information about Tongan Wei and Jufeng Puman>\n<Dayang Jingxuan; in Huihong's version of the lineage, is a descendant of; Tongan Daopi>\n<Dayang Jingxuan; is recorded in the Transmission of the Lamp as being descended through; Jufeng Puman>",
    },
    {
        "title": "Richard \"Popcorn\" Wylie", 
        "text": "Strong's \"Money (That's What I Want)\", and then \"Real Good Lovin\". He also recorded with Janie Bradford as a duo, Janard, and began working as a backing musician. He played piano on The Miracles' 1961 hit \"Shop Around\" and The Marvelettes' \"Please Mr. Postman\", and additionally worked with The Contours, Marvin Gaye, Marv Johnson, The Supremes, Martha & the Vandellas and Mary Wells. He was Motown's first head of A&R, and served as the band leader for the first Motortown Revue tour in 1962. In 1962 he left Motown after a disagreement with Gordy, who failed to mention him in", 
        "triples": "<Richard \"Popcorn\" Wylie; recorded; \"Money (That's What I Want)\", \"Real Good Lovin\">\n<Richard \"Popcorn\" Wylie; recorded with; Janie Bradford as a duo, Janard>\n<Richard \"Popcorn\" Wylie; began working as; a backing musician>\n<Richard \"Popcorn\" Wylie; played piano on; The Miracles' 1961 hit \"Shop Around\" and The Marvelettes' \"Please Mr. Postman\">\n<Richard \"Popcorn\" Wylie; worked with; The Contours, Marvin Gaye, Marv Johnson, The Supremes, Martha & the Vandellas, Mary Wells>\n<Richard \"Popcorn\" Wylie; was; Motown's first head of A&R>\n<Richard \"Popcorn\" Wylie; served as; the band leader for the first Motortown Revue tour in 1962>\n<Richard \"Popcorn\" Wylie; left Motown; in 1962 after a disagreement with Gordy>",
    },
    {
        "title": "Multilayer perceptron", 
        "text": "speech recognition, image recognition, and machine translation software, but thereafter faced strong competition from much simpler (and related) support vector machines. Interest in backpropagation networks returned due to the successes of deep learning. Multilayer perceptron A multilayer perceptron (MLP) is a class of feedforward artificial neural network. An MLP consists of, at least, three layers of nodes: an input layer, a hidden layer and an output layer. Except for the input nodes, each node is a neuron that uses a nonlinear activation function. MLP utilizes a supervised learning technique called backpropagation for training. Its multiple layers and non-linear activation distinguish", 
        "triples": "<Multilayer perceptron; is used in; speech recognition, image recognition, and machine translation software>\n<Multilayer perceptron; faced competition from; support vector machines>\n<Interest in backpropagation networks; returned due to; the successes of deep learning>\n<Multilayer perceptron; is a class of; feedforward artificial neural network>\n<Multilayer perceptron; consists of; at least three layers of nodes: an input layer, a hidden layer, an output layer>\n<each node (except input nodes) in MLP; is; a neuron that uses a nonlinear activation function>\n<Multilayer perceptron; utilizes; a supervised learning technique called backpropagation for training>\n<Multilayer perceptron; is distinguished by; multiple layers and non-linear activation>",
    },
    # 16 - 20 
    {
        "title": "Old Monroe, Missouri", 
        "text": "Monroe. Old Monroe is located at (38.931993, -90.748049). According to the United States Census Bureau, the city has a total area of , of which is land and is water. As of the census of 2010, there were 265 people, 102 households, and 68 families residing in the city. The population density was . There were 113 housing units at an average density of . The racial makeup of the city was 97.0% White, 0.4% African American, 0.4% Native American, 1.1% from other races, and 1.1% from two or more races. Hispanic or Latino of any race were 1.9% of",
        "triples": "<Old Monroe; is located at; (38.931993, -90.748049)>\n<Old Monroe; total area according to the United States Census Bureau; (missing)>\n<Old Monroe; population as of the census of 2010; 265 people, 102 households, and 68 families>\n<Old Monroe; population density; (missing)>\n<Old Monroe; had; 113 housing units at an average density of (missing)>\n<Old Monroe; had a racial makeup of; 97.0% White, 0.4% African American, 0.4% Native American, 1.1% from other races, 1.1% from two or more races>\n<Hispanic or Latino of any race; were; 1.9% of the population>", 
    },
    {
        "title": "A.D. San Carlos", 
        "text": "A.D. San Carlos Asociaci\u00f3n Deportiva San Carlos is a Costa Rican football team who currently play in the Costa Rican First Division. It is based in Ciudad Quesada, San Carlos Cant\u00f3n, north of Alajuela. Their home stadium is Estadio Carlos Ugalde \u00c1lvarez. The club was founded on 9 May 1965, after local clubs \"El Refugio\" and \"El Maravilla\" merged to become \"Selecci\u00f3n\ de San Carlos\" and winning promotion to the Primera Divisi\u00f3n in 1965. They were relegated in 1971 and stayed in the Second Division until returning at the top level in 1978. In 2004 they were relegated again after",
        "triples": "<A.D. San Carlos; full name; Asociaci\u00f3n Deportiva San Carlos>\n<A.D. San Carlos; is; a Costa Rican football team>\n<A.D. San Carlos; currently play in; the Costa Rican First Division>\n<A.D. San Carlos; is based in; Ciudad Quesada, San Carlos Cant\u00f3n, north of Alajuela>\n<A.D. San Carlos; has a home stadium at; Estadio Carlos Ugalde \u00c1lvarez>\n<A.D. San Carlos; was founded on; 9 May 1965>\n<Local clubs \"El Refugio\" and \"El Maravilla\"; merged to become; Selecci\u00f3n\ de San Carlos>\n<Selecci\u00f3n\ de San Carlos; won promotion to; the Primera Divisi\u00f3n in 1965>\n<A.D. San Carlos; was relegated in; 1971>\n<A.D. San Carlos; returned to the top level in; 1978>\n<A.D. San Carlos; was relegated again in; 2004>", 
    },
    {
        "title": "Mehrabad International Airport", 
        "text": "international flights to the new airport was completed. All international flights have now been moved to IKA. Mehrabad International Airport consists of six terminals: An aircraft engineering and maintenance company Fajr Ashian, has a maintenance hangar adjacent to main airport premises. The hangar is linked to Mehrabad Airport through a taxiway crossing \"Tehran-Karaj\" Highway. Fajr Ashian takes care of Aircraft of many companies e.g. Iran Air, Mahan Air, Meraj Airlines. It is served by two stations of the Tehran Metro: The airport is home to the head offices of Iran Air and the Iran Civil Aviation Organization. In addition the",
        "triples": "<International flights; have now been moved to; IKA>\n<Mehrabad International Airport; consists of; six terminals>\n<Fajr Ashian; is; an aircraft engineering and maintenance company>\n<Fajr Ashian; has; a maintenance hangar adjacent to main airport premises>\n<The hangar; is linked to; Mehrabad Airport through a taxiway crossing \"Tehran-Karaj\" Highway>\n<Fajr Ashian; takes care of aircraft of; many companies e.g. Iran Air, Mahan Air, Meraj Airlines>\n<Mehrabad International Airport; is served by; two stations of the Tehran Metro>\n<Mehrabad International Airport; is home to; the head offices of Iran Air and the Iran Civil Aviation Organization>\n", 
    },
    {
        "title": "CSS Shenandoah", 
        "text": "capture and sinking or bonding of thirty-eight merchant vessels, mostly New Bedford whaleships. She finally surrendered on the River Mersey, Liverpool, England, on November 6, 1865, six months after the war had ended. Her flag was the last sovereign Confederate flag to be officially furled. The \"Shenandoah\" is also known for having fired the last shot of the Civil War, across the bow of a whaler in waters off the Aleutian Islands. The vessel had three names and many owners in her lifetime of nine years. She was designed as an auxiliary composite passenger cargo vessel of 1,018 tons and",
        "triples": "<CSS Shenandoah; captured and sank or bonded; thirty-eight merchant vessels, mostly New Bedford whaleships>\n<CSS Shenandoah; finally surrendered on; the River Mersey, Liverpool, England, on November 6, 1865>\n<CSS Shenandoah; surrendered; six months after the war had ended>\n<CSS Shenandoah's flag; was; the last sovereign Confederate flag to be officially furled>\n<CSS Shenandoah; is known for; firing the last shot of the Civil War>\n<CSS Shenandoah; fired the last shot of the Civil War across; the bow of a whaler in waters off the Aleutian Islands>\n<CSS Shenandoah; had; three names and many owners in her lifetime of nine years>\n<CSS Shenandoah; was designed as; an auxiliary composite passenger cargo vessel of 1,018 tons>", 
    },
    {
        "title": "Friends", 
        "text": "Zealand on TV2 since January 2011. Netflix added all ten seasons of \"Friends\" in high definition to their streaming service in the United States on January 1, 2015. \"Friends\" has aired on different channels in the UK in their original, unedited international versions prior to their being re-edited for US broadcast and syndication. These versions, with additional footage not seen domestically, have aired on such stations as Channel 4, Sky1, E4, and Comedy Central UK. On September 4, 2011, \"Friends\" officially ended on E4 after the channel re-ran the series since 2004. Comedy Central took over the rights to air",
        "triples": "<Friends; has aired in; New Zealand on TV2 since January 2011>\n<Netflix; added all ten seasons of \"Friends\" in high definition to; their streaming service in the United States on January 1, 2015>\n<Friends; has aired on different channels in the UK in; their original, unedited international versions>\n<Original, unedited international versions; have aired on; Channel 4, Sky1, E4, and Comedy Central UK>\n<Friends; officially ended on E4 on; September 4, 2011>\n<E4; had re-ran the series since; 2004>\n<Comedy Central; took over the rights to air; Friends>", 
    },
]